version: "3.4"

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
